[project]
name = "happy-birthday-bot"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "aiogram>=3.20.0.post0",
    "google-genai>=1.18.0",
    "python-dotenv>=1.1.0",
]
